
language: node_js
node_js:
  - "0.11"
before_install:
  - npm install -g grunt-cli
  - npm install -g git://github.com/vf1/flatten.git
install:
  - npm install --production
  - flatten-packages
  - npm install
before_script: grunt --verbose
script:
  - ls $TRAVIS_BUILD_DIR
  - ls $TRAVIS_BUILD_DIR/nw
deploy:
  skip_cleanup: true
  edge: true
  provider: releases
  api-key:
    - secure: "H+d5TOQAqkOI61Qphdb4LfDWM5aWt08os0wwE9D6iIk4knopTVMdhPWmbT1JAZpHqYPvqvAFXAp9UCPCa/QrFJwe3+IdnvNAKXWiwwaoaxiSKN34ZUtdCM5qnMdoUkZh0hILfz2apQCWCGC85vmPKPiH9zv4x09EP07M2AhJROs="
  file:
    - $TRAVIS_BUILD_DIR/nw/open-media-server-0.2.0.nw
  on:
    tags: true
    all_branches: true
