
language: node_js
node_js:
  - "0.11"
before_install:
  - npm install -g grunt-cli
  - npm install -g git://github.com/vf1/flatten.git
install:
  - npm install --production
  - flatten-packages
  - npm install
before_script: grunt
